---
title: "Final Project"
author: "Anil, Alex, Laura, Ellis"
date: "4/24/2022"
output: html_document
---

```{r setup, include=FALSE}
```

```{r}
library(dplyr)
library(tidyr)
```

```{r}
# import the dataset and replace all the missing values with NAs

###project_dataset = read.csv("Mapping.Police.Violence.csv", na.strings=c("","NA"))

project_dataset <- read.csv("C:/Users/chenelli/Downloads/STA-230-Final-Project-main (1)/STA-230-Final-Project-main/Mapping_Police_Violence.csv", comment.char="#")
# select the variables of interest
project_dataset = dplyr::select(project_dataset, gender, age, race, state, agency_responsible, congressional_district_113, latitude, longitude, congressperson_party, pop_total_census_tract, pop_white_census_tract, pop_black_census_tract, pop_asian_census_tract, pop_pacific_islander_census_tract, pop_native_american_census_tract, pop_hispanic_census_tract)

#remove rows with NA values and Unknown races
project_dataset = filter(project_dataset, race != "Unknown race")
project_dataset = filter(project_dataset, race != "Non-white")
project_dataset = na.omit(project_dataset)
project_dataset = filter(project_dataset, congressperson_party == "Democrat"| congressperson_party == "Republican")

#Convert percentages to decimal
project_dataset$pop_white_census_tract <- as.numeric(sub("%", "", project_dataset$pop_white_census_tract, fixed=TRUE))/100

project_dataset$pop_black_census_tract <- as.numeric(sub("%", "", project_dataset$pop_black_census_tract, fixed=TRUE))/100

project_dataset$pop_hispanic_census_tract <- as.numeric(sub("%", "", project_dataset$pop_hispanic_census_tract, fixed=TRUE))/100

project_dataset$pop_asian_census_tract <- as.numeric(sub("%", "", project_dataset$pop_asian_census_tract, fixed=TRUE))/100

project_dataset$pop_pacific_islander_census_tract <- as.numeric(sub("%", "", project_dataset$pop_pacific_islander_census_tract, fixed=TRUE))/100

project_dataset$pop_native_american_census_tract <- as.numeric(sub("%", "", project_dataset$pop_native_american_census_tract, fixed=TRUE))/100
```

```{r}
# generate a csv file of filtered dataset
write.csv(project_dataset, "Filtered Police Violence Dataset.csv", row.names = FALSE)
```
