---
title: "Pre-Analysis Final Project Testing"
author: "Anil Alper, Ellis Chen, Laura Kiely, and Alex Porter"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(corrplot)
library(ggplot2)
library(caret)
library(tree)
library(datasets)
library(randomForest)
library(pROC)
library(tidyr)
```

```{r}
project_data <- read.csv("C7 IYSdata.csv", header=TRUE, na.strings=c(".","NA"))

project_data[project_data == "1-2 hours"] = "2 or less hours"
project_data[project_data == "0 hours"] = "2 or less hours"
project_data[project_data == "6-10 hours"] = "6 or more hours"
project_data[project_data == "11 or more hours"] = "6 or more hours"
project_data[project_data == "Strongly agree"] = "Agree"
project_data[project_data == "Strongly disagree"] = "Disagree"

#Stacked bar charts
#Change the second parameter of count and fill= command to print out different variables

#Time.HW vs Grade
d = project_data %>% dplyr::count(time.HW, grade) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = grade) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

#Time.HW vs Gender
d = project_data %>% dplyr::count(time.HW, gender) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = gender) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs Time.work 
d = project_data %>% dplyr::count(time.HW, time.work) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = time.work) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs time.no.adult
d = project_data %>% dplyr::count(time.HW, time.no.adult) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = time.no.adult) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs time.school.act
d = project_data %>% dplyr::count(time.HW, time.school.act) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = time.school.act) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs time.noschool.act 
d = project_data %>% dplyr::count(time.HW, time.noschool.act) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = time.noschool.act) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs time.reading 
d = project_data %>% dplyr::count(time.HW, time.reading) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = time.reading) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 
#Time.HW vs time.church 
d = project_data %>% dplyr::count(time.HW, time.church) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = time.church) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs X30dr.driving 
d = project_data %>% dplyr::count(time.HW, X30dr.driving) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = X30dr.driving) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs values.drug 
d = project_data %>% dplyr::count(time.HW, values.drug) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = values.drug) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs excite 
d = project_data %>% dplyr::count(time.HW, excite) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = excite) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs hard.work 
d = project_data %>% dplyr::count(time.HW, hard.work) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = hard.work) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs Pop.cig 
d = project_data %>% dplyr::count(time.HW, Pop.cig) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = Pop.cig) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs best.school 
d = project_data %>% dplyr::count(time.HW, best.school) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = best.school) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs talk.adult 
d = project_data %>% dplyr::count(time.HW, talk.adult) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = talk.adult) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs grades 
d = project_data %>% dplyr::count(time.HW, grades) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = grades) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.happy 
d = project_data %>% dplyr::count(time.HW, home.happy) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.happy) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.al.drug 
d = project_data %>% dplyr::count(time.HW, home.al.drug) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.al.drug) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.close 
d = project_data %>% dplyr::count(time.HW, home.close) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.close) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.talk 
d = project_data %>% dplyr::count(time.HW, home.talk) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.talk) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.support 
d = project_data %>% dplyr::count(time.HW, home.support) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.support) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 
# Time.HW vs home.know
d = project_data %>% dplyr::count(time.HW, home.know) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.know) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.chores 
d = project_data %>% dplyr::count(time.HW, home.chores) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.chores) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.wrong 
d = project_data %>% dplyr::count(time.HW, home.wrong) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.wrong) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs home.praise 
d = project_data %>% dplyr::count(time.HW, home.praise) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = home.praise) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 

# Time.HW vs Wpdrink 
d = project_data %>% dplyr::count(time.HW, Wpdrink) %>% group_by(time.HW)
d$sum_group = ave(d$n, d$time.HW, FUN=sum)
d = mutate(d, percentages = paste0(round(n/sum_group * 100), "%")) 
ggplot(d) + aes(time.HW, n, fill = Wpdrink) + 
geom_col(width = .7) + 
geom_text(aes(label = percentages), position = position_stack(vjust = 0.5), size = 3.5) 
```

```{r}
project_data_all <- read.csv("~/Downloads/STA-230-Final-Project-main 11/C7 IYSdata.csv", header=TRUE, na.strings=c(".","NA", "-1"))
project_data_all[project_data_all == "1-2 hours"] = "2 or less hours"
project_data_all[project_data_all == "0 hours"] = "2 or less hours"
project_data_all[project_data_all == "6-10 hours"] = "6 or more hours"
project_data_all[project_data_all == "11 or more hours"] = "6 or more hours"
project_data_all = subset(project_data_all, !is.na(time.HW))
project_data_all[is.na(project_data_all)] = "NA"
```

```{r}
set.seed(123)
trainIndex = createDataPartition(project_data_all$time.HW, p = 0.7, list = FALSE, times=1)
numericTrainAll = project_data_all[trainIndex,]
numericTestAll = project_data_all[-trainIndex,]
```

```{r}
numericTrainAll$time.HW = factor(numericTrainAll$time.HW) 
forestAll1 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 1, do.trace = TRUE, set.seed(123))
forestAll2 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 2, do.trace = TRUE, set.seed(123))
forestAll3 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 3, do.trace = TRUE, set.seed(123))
forestAll4 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 4, do.trace = TRUE, set.seed(123))
forestAll5 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 5, do.trace = TRUE, set.seed(123))
forestAll6 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 6, do.trace = TRUE, set.seed(123))
forestAll7 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 7, do.trace = TRUE, set.seed(123))
forestAll8 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 8, do.trace = TRUE, set.seed(123))
forestAll9 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 9, do.trace = TRUE, set.seed(123))
forestAll10 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 10, do.trace = TRUE, set.seed(123))
forestAll11 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 11, do.trace = TRUE, set.seed(123))
forestAll12 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 12, do.trace = TRUE, set.seed(123))
forestAll13 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 13, do.trace = TRUE, set.seed(123))
forestAll14 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 14, do.trace = TRUE, set.seed(123))
forestAll15 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 15, do.trace = TRUE, set.seed(123))
```
Plotting Accuracy 
```{r}
AllDf <- data.frame(mtry  = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                  OOBError = c(43.5, 41.82, 41.31, 41.15, 41.03, 41.15, 40.88, 41.11, 40.76, 41.11, 41.43, 41.5, 41.62, 40.84, 41.97)
                  )
AccuracyPlotAll = ggplot(AllDf, aes(x=mtry, y=OOBError, label=OOBError)) +
  geom_point(size=2, shape=1, stroke = 1) +
  geom_text(hjust=1.25, vjust=0) +
  scale_x_continuous(breaks = seq(-1, 15, by = 1), name = "Number of Variables") +
  scale_y_continuous(name = "Out of Bag Error (%)") +
  coord_cartesian(xlim=c(0.5,15)) +
  ggtitle("Out of Bag Error and Number of Variables Sampled at Splits (All Variables)") 
AccuracyPlotAll
```
AUC Plot
```{r}
predictionsAll1 <- as.numeric(predict(forestAll1, numericTrainAll, type = 'response'))
roc.multiAll1 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll1, 
                            percent=TRUE)
predictionsAll2 <- as.numeric(predict(forestAll2, numericTrainAll, type = 'response'))
roc.multiAll2 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll2, 
                            percent=TRUE)
predictionsAll3 <- as.numeric(predict(forestAll3, numericTrainAll, type = 'response'))
roc.multiAll3 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll3, 
                            percent=TRUE)
predictionsAll4 <- as.numeric(predict(forestAll4, numericTrainAll, type = 'response'))
roc.multiAll4 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll4, 
                            percent=TRUE)
predictionsAll5 <- as.numeric(predict(forestAll5, numericTrainAll, type = 'response'))
roc.multiAll5 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll5, 
                            percent=TRUE)
predictionsAll6 <- as.numeric(predict(forestAll6, numericTrainAll, type = 'response'))
roc.multiAll6 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll6, 
                            percent=TRUE)
predictionsAll7 <- as.numeric(predict(forestAll7, numericTrainAll, type = 'response'))
roc.multiAll7 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll7, 
                            percent=TRUE)
predictionsAll8 <- as.numeric(predict(forestAll8, numericTrainAll, type = 'response'))
roc.multiAll8 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll8, 
                            percent=TRUE)
predictionsAll9 <- as.numeric(predict(forestAll9, numericTrainAll, type = 'response'))
roc.multiAll9 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll9, 
                            percent=TRUE)
predictionsAll10 <- as.numeric(predict(forestAll10, numericTrainAll, type = 'response'))
roc.multiAll10 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll10, 
                            percent=TRUE)
predictionsAll11 <- as.numeric(predict(forestAll11, numericTrainAll, type = 'response'))
roc.multiAll11 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll11, 
                            percent=TRUE)
predictionsAll12 <- as.numeric(predict(forestAll12, numericTrainAll, type = 'response'))
roc.multiAll12 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll12, 
                            percent=TRUE)
predictionsAll13 <- as.numeric(predict(forestAll13, numericTrainAll, type = 'response'))
roc.multiAll13 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll13, 
                            percent=TRUE)
predictionsAll14 <- as.numeric(predict(forestAll14, numericTrainAll, type = 'response'))
roc.multiAll14 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll14, 
                            percent=TRUE)
predictionsAll15 <- as.numeric(predict(forestAll15, numericTrainAll, type = 'response'))
roc.multiAll15 <- multiclass.roc(numericTrainAll$time.HW, predictionsAll15, 
                            percent=TRUE)
AucdfAll <- data.frame(mtry  = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                  MulticlassAUC = c(roc.multiAll1$auc, roc.multiAll2$auc, roc.multiAll3$auc, roc.multiAll4$auc, roc.multiAll5$auc, roc.multiAll6$auc, roc.multiAll7$auc, roc.multiAll8$auc, roc.multiAll9$auc, roc.multiAll10$auc, roc.multiAll11$auc, roc.multiAll12$auc, roc.multiAll13$auc, roc.multiAll14$auc, roc.multiAll15$auc)
                  )
AucdfAll
AUCPlotAll = ggplot(AucdfAll, aes(x=mtry, y=MulticlassAUC)) +
  geom_point(size=2, shape=1, stroke = 1) +
  #geom_text(hjust=.5, vjust=1) +
  scale_x_continuous(breaks = seq(-1, 15, by = 1), name = "Number of Variables") +
  scale_y_continuous(name = "AUC") +
  coord_cartesian(xlim=c(0.5,15)) +
  ggtitle("AUC and Number of Variables Sampled at Splits, All") 
AUCPlotAll
print("How is this possible?")
```
Selected Variables
```{r}
# With NA values
numericTrainSelected = select(numericTrainAll, time.school.act, time.no.adult, age, grade, time.reading, time.friend, time.noschool.act, talk.adult, Pop.cig, home.know, time.work, best.school, gender, values.drug, time.church, home.chores, home.wrong, home.talk, Pop.drink, home.happy, home.al.drug, home.praise, excite, grades, Pop.marijuana, home.support, home.close, hard.work, X30dr.driving, Wpdrink, time.HW)
numericTestSelected = select(numericTestAll, time.school.act, time.no.adult, age, grade, time.reading, time.friend, time.noschool.act, talk.adult, Pop.cig, home.know, time.work, best.school, gender, values.drug, time.church, home.chores, home.wrong, home.talk, Pop.drink, home.happy, home.al.drug, home.praise, excite, grades, Pop.marijuana, home.support, home.close, hard.work, X30dr.driving, Wpdrink, time.HW)
forestSelect1 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 1, do.trace = TRUE, set.seed(123))
forestSelect2 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 2, do.trace = TRUE, set.seed(123))
forestSelect3 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 3, do.trace = TRUE, set.seed(123))
forestSelect4 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 4, do.trace = TRUE, set.seed(123))
forestSelect5 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 5, do.trace = TRUE, set.seed(123))
forestSelect6 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 6, do.trace = TRUE, set.seed(123))
forestSelect7 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 7, do.trace = TRUE, set.seed(123))
forestSelect8 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 8, do.trace = TRUE, set.seed(123))
forestSelect9 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 9, do.trace = TRUE, set.seed(123))
forestSelect10 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 10, do.trace = TRUE, set.seed(123))
forestSelect11 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 11, do.trace = TRUE, set.seed(123))
forestSelect12 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 12, do.trace = TRUE, set.seed(123))
forestSelect13 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 13, do.trace = TRUE, set.seed(123))
forestSelect14 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 14, do.trace = TRUE, set.seed(123))
forestSelect15 = randomForest(time.HW ~., data = numericTrainSelected, importance = TRUE, ntree = 1000, mtry = 15, do.trace = TRUE, set.seed(123))
```

```{R}
# Without NA Values
set.seed(123)
project_data = read.csv("C7 IYSdata.csv", header=TRUE, na.strings=c(".", "NA"))
project_data[project_data == "1-2 hours"] = "2 or less hours"
project_data[project_data == "0 hours"] = "2 or less hours"
project_data[project_data == "6-10 hours"] = "6 or more hours"
project_data[project_data == "11 or more hours"] = "6 or more hours"
project_data[project_data == "-1"] = NA
project_data[project_data == "Strongly agree"] = "Agree"
project_data[project_data == "Strongly disagree"] = "Disagree"
sub_project_data = select(project_data, time.school.act, time.no.adult, age, grade, time.reading, time.friend, time.noschool.act, talk.adult, Pop.cig, home.know, time.work, best.school, gender, values.drug, time.church, home.chores, home.wrong, home.talk, Pop.drink, home.happy, home.al.drug, home.praise, excite, grades, Pop.marijuana, home.support, home.close, hard.work, X30dr.driving, Wpdrink, time.HW)
sub_project_data = na.omit(sub_project_data)
trainIndex = createDataPartition(sub_project_data$time.HW, p = 0.7, list = FALSE, times=1)
projectTrain = sub_project_data[trainIndex,]
projectTrain$time.HW = factor(projectTrain$time.HW) 
forest2 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 2, do.trace = TRUE)
forest3 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 3, do.trace = TRUE)
forest4 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 4, do.trace = TRUE)
forest5 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 5, do.trace = TRUE)
forest6 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 6, do.trace = TRUE)
forest7 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 7, do.trace = TRUE)
varImpPlot(forest, sort=TRUE)
```

Testing---forestSelect4
```{r}
project.pred = predict(forestSelect4, numericTestSelected)
head(project.pred)
#with(numericTestSelected, table(project.pred, time.HW))
table(observed = numericTestSelected[, "time.HW"], predicted = project.pred)
Accuracy = (557 + 88 + 16)/(557 + 213 + 103 + 53 + 88 + 40 + 7 + 15 + 16) = 0.6053114
```

```{r}
SelectDf <- data.frame(mtry  = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                  OOBError = c(40.52, 40.52, 40.68, 40.41, 40.56, 40.6, 40.96, 41.39, 41.43, 40.99, 41.62, 41.23, 42.09, 42.09, 41.78)
                  )
AccuracyPlotSelect = ggplot(SelectDf, aes(x=mtry, y=OOBError, label=OOBError)) +
  geom_point(size=2, shape=1, stroke = 1) +
  geom_text(hjust=1.2, vjust=0) +
  scale_x_continuous(breaks = seq(-1, 15, by = 1), name = "Number of Variables") +
  scale_y_continuous(name = "Out of Bag Error (%)") +
  coord_cartesian(xlim=c(0.5,15)) +
  ggtitle("Out of Bag Error and Number of Variables Sampled at Splits (All Variables)") 
AccuracyPlotSelect
```
