---
title: "Final Project Map"
output: word_document
date: '2022-05-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(maps)
```

```{r}
PVData <- read.csv("~/Downloads/STA-230-Final-Project-main/Filtered Police Violence Dataset.csv", header=FALSE)
   View(PVData)
   names(PVData) <- PVData[1,]
PVData <- PVData[-1,]
```

```{r}
###Changing header
PVData$longitude = as.character(PVData$longitude)
PVData$latitude = as.character(PVData$latitude)

PVData$longitude = as.numeric(PVData$longitude)
PVData$latitude = as.numeric(PVData$latitude)
```

```{r}
###Map with states
MainStates <- map_data("state")
#View(MainStates)
#Excluding Alaska and Hawaii
PVData = filter(PVData, latitude < 50)
PVData = filter(PVData, longitude > -140)


###Creating color by race


###Map Making
g = ggplot() + 
  geom_polygon(data=MainStates, aes(x=long, y=lat, group=group),
                color="black", fill="white",  size = .3,) +
  geom_point(data = PVData, aes(x=longitude, y=latitude, color = race), size = .2) +
  ggtitle("U.S. Police Killings Map by Race") +
  guides(colour = guide_legend(override.aes = list(size=5))) +
  theme_void()  

g

```