---
title: "All Variable Analysis"
output: html_document
date: '2022-05-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(corrplot)
library(ggplot2)
library(tree)
library(datasets)
library(randomForest)
library(pROC)
library(tidyr)
```

```{r}
project_data_all <- read.csv("~/Downloads/STA-230-Final-Project-main 11/C7 IYSdata.csv", header=TRUE, na.strings=c(".","NA", "-1"))

project_data_all = select(project_data_all, time.school.act, time.no.adult, age, grade, time.reading, time.friend, time.noschool.act, talk.adult, Pop.cig, home.know, time.work, best.school, gender, values.drug, time.church, home.chores, home.wrong, home.talk, Pop.drink, home.happy, home.al.drug, home.praise, excite, grades, Pop.marijuana, home.support, home.close, hard.work, X30dr.driving, Wpdrink, time.HW)

project_data_all[project_data_all == "1-2 hours"] = "2 or less hours"
project_data_all[project_data_all == "0 hours"] = "2 or less hours"
project_data_all[project_data_all == "6-10 hours"] = "more than 2 hours"
project_data_all[project_data_all == "11 or more hours"] = "more than 2 hours"
project_data_all[project_data_all == "3-5 hours"] = "more than 2 hours"

project_data_all = subset(project_data_all, !is.na(time.HW))
project_data_all[is.na(project_data_all)] = "NA"

```

```{r}
set.seed(123)
trainIndex = createDataPartition(project_data_all$time.HW, p = 0.7, list = FALSE, times=1)

numericTrainAll = project_data_all[trainIndex,]
numericTestAll = project_data_all[-trainIndex,]

```

```{r}
numericTrainAll$time.HW = factor(numericTrainAll$time.HW) 
numericTestAll$time.HW = factor(numericTestAll$time.HW) 


forestAll1 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 1, do.trace = TRUE, set.seed(123))

forestAll2 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 2, do.trace = TRUE, set.seed(123))

forestAll3 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 3, do.trace = TRUE, set.seed(123))

forestAll4 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 4, do.trace = TRUE, set.seed(123))

forestAll5 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 5, do.trace = TRUE, set.seed(123))

forestAll6 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 6, do.trace = TRUE, set.seed(123))

forestAll7 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 7, do.trace = TRUE, set.seed(123))

forestAll8 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 8, do.trace = TRUE, set.seed(123))

forestAll9 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 9, do.trace = TRUE, set.seed(123))

forestAll10 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 10, do.trace = TRUE, set.seed(123))

forestAll11 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 11, do.trace = TRUE, set.seed(123))

forestAll12 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 12, do.trace = TRUE, set.seed(123))

forestAll13 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 13, do.trace = TRUE, set.seed(123))

forestAll14 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 14, do.trace = TRUE, set.seed(123))

forestAll15 = randomForest(time.HW ~., data = numericTrainAll, importance = TRUE, ntree = 1000, mtry = 15, do.trace = TRUE, set.seed(123))

```
```{r}
forestAll1
forestAll2
forestAll3
forestAll4
forestAll5
forestAll6
forestAll7
forestAll8
forestAll9
forestAll10
forestAll11
forestAll12
forestAll13
forestAll14
forestAll15
```
Plotting Accuracy 
```{r, fig.height=3.5}
#Creating Plot of mtry and error
SelectErrorTotal <- data.frame(mtry  = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                  OOBError = c(35.1, 33.61, 34.16, 34, 34.47, 33.96, 34.78, 34.31, 35.29, 34.98, 35.14, 34.74, 34.43, 34.47, 34.39))

AccuracyPlotAll = ggplot(SelectErrorTotal, aes(x=mtry, y=OOBError, label=OOBError)) +
  geom_point(size=2, shape=1, stroke = 1) +
  geom_text(hjust=1.25, vjust=0) +
  scale_x_continuous(breaks = seq(-1, 15, by = 1), name = "Number of Variables") +
  scale_y_continuous(name = "Out of Bag Error (%)") +
  coord_cartesian(xlim=c(0.5,15)) +
  ggtitle("Out of Bag Error and Number of Variables Sampled at Splits (30 Variables)") 

AccuracyPlotAll

#Creating plot of mtry and class error 
SelectError2less <- data.frame(mtry  = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                  OOBError = c(0.1144244, 0.1976422, 0.2212205, 0.2274619, 0.2350902, 0.2274619, 0.2392510,0.2309293,0.2482663,0.2489598,0.2496533,0.2441054,0.2413315,0.2510402,0.2427184 ))

SelectError2more <- data.frame(mtry  = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                  OOBError = c(0.6579658, 0.5157516, 0.4977498, 0.4860486, 0.4869487, 0.4851485, 0.4887489,0.4887489,0.4887489,0.4806481,0.4833483,0.4815482,0.4779478,0.4662466,0.4752475    ))

AccuracyPlot2less = ggplot(SelectError2less, aes(x=mtry, y=OOBError)) +
  geom_point(size=2, shape=1, stroke = 1) +
  #geom_text(hjust=1.25, vjust=0) +
  scale_x_continuous(breaks = seq(-1, 15, by = 1), name = "Number of Variables") +
  scale_y_continuous(name = "Out of Bag Error") +
  #coord_cartesian(xlim=c(0.5,15)) +
  ggtitle("0-2 Class Error by # of Variables Sampled") 

AccuracyPlot2more = ggplot(SelectError2more, aes(x=mtry, y=OOBError)) +
  geom_point(size=2, shape=1, stroke = 1) +
  #geom_text(hjust=1.25, vjust=0) +
  scale_x_continuous(breaks = seq(-1, 15, by = 1), name = "Number of Variables") +
  scale_y_continuous(name = "Out of Bag Error") +
  #coord_cartesian(xlim=c(0.5,15)) +
  ggtitle("2+ Class Error by # of Variables Sampled") 

```
```{r}
AccuracyPlotAll
AccuracyPlot2more
AccuracyPlot2less
```
Confusion Matrix/Sensitivity/Specificity/Accuracy---Training
```{r, fig.height=3.5}
library(caret)

p1 <- predict(forestAll1, numericTrainAll)
confusionMatrix(p1, numericTrainAll$ time.HW)

p2 <- predict(forestAll2, numericTrainAll)
confusionMatrix(p2, numericTrainAll$ time.HW)

p3 <- predict(forestAll3, numericTrainAll)
confusionMatrix(p3, numericTrainAll$ time.HW)

p4 <- predict(forestAll4, numericTrainAll)
confusionMatrix(p4, numericTrainAll$ time.HW)

p5 <- predict(forestAll5, numericTrainAll)
confusionMatrix(p5, numericTrainAll$ time.HW)

p6 <- predict(forestAll6, numericTrainAll)
confusionMatrix(p6, numericTrainAll$ time.HW)
```

Confusion Matrix/Sensitivity/Accuracy---Testing
```{r, fig.height=3.5}
library(caret)

test1 <- predict(forestAll1, numericTestAll)
confusionMatrix(test1, numericTestAll$ time.HW)

test2 <- predict(forestAll2, numericTestAll)
confusionMatrix(test2, numericTestAll$ time.HW)

test3 <- predict(forestAll3, numericTestAll)
confusionMatrix(test3, numericTestAll$ time.HW)

test4 <- predict(forestAll4, numericTestAll)
confusionMatrix(test4, numericTestAll$ time.HW)

test5 <- predict(forestAll5, numericTestAll)
confusionMatrix(test5, numericTestAll$ time.HW)

test6 <- predict(forestAll6, numericTestAll)
confusionMatrix(test6, numericTestAll$ time.HW)
```

ROC---Training
```{r}
#Creating ROC from training dataset and forest models
rf.roc1 <-roc (numericTrainAll$time.HW, forestAll1$votes[,2])
rf.roc2 <-roc (numericTrainAll$time.HW, forestAll2$votes[,2])
rf.roc3 <-roc (numericTrainAll$time.HW, forestAll3$votes[,2])
rf.roc4 <-roc (numericTrainAll$time.HW, forestAll4$votes[,2])
rf.roc5 <-roc (numericTrainAll$time.HW, forestAll5$votes[,2])
rf.roc6 <-roc (numericTrainAll$time.HW, forestAll6$votes[,2])

#Printing ROC Plots Together, with optimal threshold and AUC
plot(rf.roc1, print.thres = "best", print.auc = TRUE, main = "ROC Curve: mtry = 1")
plot(rf.roc2, print.thres = "best", print.auc = TRUE, main = "ROC Curve: mtry = 2")
plot(rf.roc3, print.thres = "best", print.auc = TRUE, main = "ROC Curve: mtry = 3")
plot(rf.roc4, print.thres = "best", print.auc = TRUE, main = "ROC Curve: mtry = 4")
plot(rf.roc5, print.thres = "best", print.auc = TRUE, main = "ROC Curve: mtry = 5")
plot(rf.roc6, print.thres = "best", print.auc = TRUE, print.auc.x = .5, print.auc.y = .4, main = "ROC Curve: mtry = 6")

```
ROC---Testing---??
```{r}
#Creating ROC from testing dataset and forest models

```


