---
title: "Pre-Analysis Final Project Testing"
author: "Anil Alper, Ellis Chen, Laura Kiely, and Alex Porter"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(corrplot)
library(ggplot2)
library(caret)
library(tree)
library(datasets)
```

```{r}
original_data = read.csv("C7 IYSdata.csv", header=TRUE, na.strings=c(".","NA"))
project_data <- read.csv("C7 IYSdata.csv", header=TRUE, na.strings=c("-1","NA"))
project_data = dplyr::select(project_data, gender, time.reading, time.HW, grade, time.no.adult, time.noschool.act, time.school.act)

#Response Variables
#1. time HW: grade, 
# important variables:
#2. best school 
# important variables:
#3. grades
# important variables:

project_data[project_data == "1-2 hours"] = "2 or less hours"
project_data[project_data == "0 hours"] = "2 or less hours"
project_data[project_data == "6-10 hours"] = "6 or more hours"
project_data[project_data == "11 or more hours"] = "6 or more hours"
project_data[project_data == "Strongly agree"] = "Agree"
project_data[project_data == "Strongly disagree"] = "Disagree"
```

```{R}
set.seed(123)
trainIndex = createDataPartition(project_data$time.HW, p = 0.7, list = FALSE, times=1)
projectTrain = project_data[trainIndex,]
projectTest = project_data[-trainIndex,]
project.model = train(time.HW ~., data=projectTrain, ntree=10)
project.pred = predict(project.model, projectTest)
with(projectTest, table(project.pred, time.HW))
```

```{R}
set.seed(123)
project_data = read.csv("C7 IYSdata.csv", header=TRUE, na.strings=c(".","NA"))
project_data[project_data == "1-2 hours"] = "2 or less hours"
project_data[project_data == "0 hours"] = "2 or less hours"
project_data[project_data == "6-10 hours"] = "6 or more hours"
project_data[project_data == "11 or more hours"] = "6 or more hours"
project_data[project_data == "Strongly agree"] = "Agree"
project_data[project_data == "Strongly disagree"] = "Disagree"
sub_project_data = dplyr::select(project_data, time.work, time.no.adult, time.friend, time.school.act, time.reading, time.church, time.excersize, time.HW)
trainIndex = createDataPartition(sub_project_data$time.HW, p = 0.7, list = FALSE, times=1)
projectTrain = sub_project_data[trainIndex,]
projectTest = sub_project_data[-trainIndex,]
project.model = train(time.HW ~., data=projectTrain, ntree=100)
project.pred = predict(project.model, projectTest)
with(projectTest, table(project.pred, time.HW))
```

```{R}
# With NA values
set.seed(123)
project_data = read.csv("C7 IYSdata.csv", header=TRUE, na.strings=c(".","NA"))
project_data[project_data == "1-2 hours"] = "2 or less hours"
project_data[project_data == "0 hours"] = "2 or less hours"
project_data[project_data == "6-10 hours"] = "6 or more hours"
project_data[project_data == "11 or more hours"] = "6 or more hours"
project_data = subset(project_data, !is.na(time.HW))
project_data[project_data == "Strongly agree"] = "Agree"
project_data[project_data == "Strongly disagree"] = "Disagree"
sub_project_data = dplyr::select(project_data, time.no.adult, time.friend, time.school.act, time.reading, time.church, time.excersize, time.HW)
trainIndex = createDataPartition(sub_project_data$time.HW, p = 0.7, list = FALSE, times=1)
projectTrain = sub_project_data[trainIndex,]
projectTrain$time.HW = factor(projectTrain$time.HW) 
forest = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 2, do.trace = TRUE)
varImpPlot(forest, sort=TRUE)
```

```{R}
# Without NA Values
set.seed(123)
project_data = read.csv("C7 IYSdata.csv", header=TRUE, na.strings=c(".","NA"))
project_data[project_data == "1-2 hours"] = "2 or less hours"
project_data[project_data == "0 hours"] = "2 or less hours"
project_data[project_data == "6-10 hours"] = "6 or more hours"
project_data[project_data == "11 or more hours"] = "6 or more hours"
project_data[project_data == "-1"] = NA
project_data[project_data == "Strongly agree"] = "Agree"
project_data[project_data == "Strongly disagree"] = "Disagree"
sub_project_data = dplyr::select(project_data, time.work, time.no.adult, time.friend, time.school.act, time.reading, time.church, time.excersize, time.HW)
sub_project_data = na.omit(sub_project_data)
trainIndex = createDataPartition(sub_project_data$time.HW, p = 0.7, list = FALSE, times=1)
projectTrain = sub_project_data[trainIndex,]
projectTrain$time.HW = factor(projectTrain$time.HW) 
forest2 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 2, do.trace = TRUE)
forest4 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 4, do.trace = TRUE)
forest6 = randomForest(time.HW ~., data = projectTrain, importance = TRUE, ntree = 100, mtry = 6, do.trace = TRUE)
varImpPlot(forest, sort=TRUE)
```
